### ISSUE TITLE
Redesign reporting

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/abort-mission#314]
### Done criteria
1. Telemetry data set is extended to be able to contain:
    1. Thread name if available
    2. Exception message/stack trace if available
    3. Parameters used for the test case if available
2. Advanced filtering is added to flight evaluation reports
    1. Based on time to filter to tests running at the same time
    2. Based on thread name
3. Test case details are extended in the reports to show each execution in separate line including:
    1. Thread name
    2. Start - end
    3. Parameters
    4. Outcome
4. Timestamps are updated to use epoch seconds in report JSON

### Tasks
- [x] Stage execution results extended to contain new information
  - [x] New implementation
  - [x] Clean-up
- [x] Boosters are updated to collect additional information
  - [x] Cucumber
  - [x] JUnit
  - [x] Jupiter
  - [x] TestNG
- [x] Reporting is updated to export additional data collected
- [x] Timestamp formats are updated in JSON
- [x] JSON schema is updated
- [x] Filtering is added to reports
    - [x] Time based
    - [x] Thread name based
    - [x] Class/Feature based
    - [x] Method/Scenario based
    - [x] Matcher based
- [x] Test case details updated in reports
- [x] Tests updated for affected code
- [x] Documentation updated
