### ISSUE TITLE
Add execution summary stats to the flight evaluation report

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/abort-mission#388]
### Done criteria
- Flight evaluation report calculates and displays the total duration between the start and end times shown in the header
- The short outcome counters in the footer is removed
- New section is added to the Flight Evaluation Report
  - Calculating and displaying time stats and counters of each outcome as well as all of them in total (min, max, avg, sum)
  - Displaying quick links to exclude (or remove exclusion of) outcomes

### Tasks

- [x] Total duration calculated
- [x] Outcome based stats calculated
- [x] New section added
    - [x] Layout
    - [x] Stats for each outcome
    - [x] Total stats
    - [x] Exclusion links
- [x] Tests updated
- [ ] Documentation updated
