### ISSUE TITLE
Examples to show proof of concept with integration tips

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/abort-mission#402]
### Done criteria

1. New repository created
2. Example integrations added for
    1. Gradle using
        1. JUnit4
        2. JUnit Jupiter
        3. TestNG
        4. Cucumber
    2. Maven using JUnit Jupiter
3. Mentioned on the wiki 

### Tasks

- [ ] New repository created
- [ ] Gradle examples created
    - [ ] JUnit4
    - [ ] JUnit Jupiter
    - [ ] TestNG
    - [ ] Cucumber
- [ ] Maven example created
- [ ] Wiki updated
